# Imagen base
FROM python:3.10-slim

# Crear el directorio de trabajo
WORKDIR /app

# Instalar dependencias del sistema necesarias para mysqlclient y pip
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Copiar el proyecto Django
COPY ../mercury_proj /app

# Instalar dependencias de Python
RUN pip install --no-cache-dir -r requirements.txt

# Exponer puerto
EXPOSE 8000

# Comando por defecto
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
