FROM debian

COPY src /opt/src/

RUN cd /opt/src/; chmod 777 prepare.sh execute.sh init.sql initMariaDB.sh;
RUN cd /opt/src/; ./prepare.sh; 

EXPOSE 3306

CMD ["bash"]
ENTRYPOINT ["/opt/src/execute.sh"]