# Imagen base mínima
FROM debian

COPY src/init.sql /docker-entrypoint-initdb.d/
COPY src /opt/src/

RUN cd /opt/src/; chmod 777 prepare.sh; chmod 777 initDB.sh; ./prepare.sh; ./initDB.sh;

# Comando por defecto al iniciar el contenedor
CMD ["bash"]
ENTRYPOINT ["/opt/src/execute.sh"]