FROM debian

COPY src /opt/src/
COPY ./mercury_proj /opt/src/app

RUN cd /opt/src/; chmod 777 prepare.sh; 
RUN cd /opt/src/; ./prepare.sh;

EXPOSE 8000

CMD ["bash"]
ENTRYPOINT ["/opt/src/execute.sh"]
